Batch apply row annotations
broadinstitute/hail-elasticsearch-pipelines pull request #247
Opened 2021-06-07 04:45 UTC by illusional

Implements #242.

Brief summary of changes:

- The row_annotation returns a data class that stores properties
- Allows a list of requirements, rather than just the single requirement
- Apply changes in annotate_all, rather than in the row_annotation by:
  - Applying "non-dependent" annotations in rounds until all annotations have been applied, or a circular dependency is detected.
- Row annotations that use the selected_ref_data, pull it from a cached attribute.

From some rough testing (thanks @tommyli), we saw:

- about 2-4 times speedup during the annotation;
- 70-75% reduction in network traffic (I presume when pulling reference data);
- Still about 15% cpu utilisation (over 2 cpus in the spark cluster).

2021-06-29 18:20 UTC, hanars requested changes
Thanks so much for submitting this! Really excited for the performance gains, I just have some style/ maintainability change requests

2021-06-29 18:20 UTC, hanars commented on luigi_pipeline/lib/model/seqr_mt_schema.py
> +        # it if it doesn't get get accessed after an update to self.mt
this comment would be more helpful as a docstring for the `_selected_ref_data` property

2021-06-29 18:20 UTC, hanars commented on luigi_pipeline/lib/model/base_mt_schema.py
> +        rounds: List[List[RowAnnotation]] = [self.all_annotation_fns()]
the name `rounds` is a bit confusing, and I think what you are achieving via a list of lists thats modified during iteration would be much cleaner with a recursive helper function. Let me know if you have any questions about that, I'm happy to help code that out for you

2021-06-29 18:20 UTC, hanars commented on luigi_pipeline/lib/model/base_mt_schema.py
> +        print(f'Will attempt to apply {len(rounds[0])} row annotations')
we use `loggger`, not `print` for logging messages. Anywhere that used `print` for debugging reasons can probably taken out, and anywhere that had useful information for production can get switched to `logger.info`

2021-06-30 14:49 UTC, mike-w-wilson commented
Thanks for these updates @illusional! We discussed this PR in person and actually prefer the previous commit with the exception of the print->logger and docstring updates. Apologies for the extra work caused but we really appreciate the improvements. Could you roll back to https://github.com/broadinstitute/hail-elasticsearch-pipelines/pull/247/commits/5eeb5a9841cb762bd802dfd41ec2b12f188197dc and just address the previous comments on print and the docstrings? Thanks!

2021-07-01 00:02 UTC, illusional commented
Hey @mike-w-wilson and @hanars, thanks for reviewing those additional changes. I'm curious why you didn't like the refactor? I think preparing the list of annotations to apply is cleaner, as you get essentially a set of instructions to apply which is easier to test.

I've reverted the change, and applied the review fixes.

2021-07-30 00:37 UTC, illusional commented
Hi @mike-w-wilson and @hanars, any update here?

2021-07-30 18:22 UTC, mike-w-wilson approved these changes
Sorry @illusional, this slipped through. I'm going to merge it with master now!

2021-07-30 18:22 UTC, merged