Add sample_qs_{X}_to_{Y} field and update transcriptConsequenceTerms field.
broadinstitute/hail-elasticsearch-pipelines pull request #257
Opened 2021-07-20 20:15 UTC by ShifaSZ

See details in issue: https://github.com/broadinstitute/seqr-private/issues/1019

2021-07-20 20:16 UTC, ShifaSZ commented on sv_pipeline/genome/load_data.py
> +        lambda x: x[MAJOR_CONSEQ] != 'NEAREST_TSS'))),
These are just changes for using constant field names.

2021-07-20 20:18 UTC, ShifaSZ commented on sv_pipeline/genome/load_data.py
> +        SV_TYPE: rows.alleles[1].replace('[<>]', '').split(':', 2)}
Just change for using constant field names `SORTED_TRANS_CONSEQ`, `MAJOR_CONSEQ`, and `SV_TYPE`.

2021-07-20 20:22 UTC, ShifaSZ commented
An example variant imported to the Elasticsearch:
```
{
  "_index": "r0486_cmg_gcnv__structural_variants__wgs__grch38__20210720",
  "_type": "_doc",
  "_id": "g51lxXoBi-gUVj-0g-5l",
  "_score": 1.0,
  "_source": {
    "contig": "8",
    "sc": 23,
    "sf": 0.016106,
    "sn": 1428,
    "start": 77815735,
    "end": 77816226,
    "sv_callset_Het": 23,
    "sv_callset_Hom": 0,
    "pos": 77815735,
    "filters": [
      "FAIL_minGQ"
    ],
    "xpos": 8077815735,
    "xstart": 8077815735,
    "xstop": 8077816226,
    "svType": "DEL",
    "transcriptConsequenceTerms": [
      "DEL",
      "NEAREST_TSS"
    ],
    "geneIds": [],
    "samples_no_call": [],
    "samples_num_alt_1": [
      "GLE_4292_4_3",
      "GLE-4778-4-2-a",
      "HIL_A5192_12_1",
      "GLE_4292_4_1"
    ],
    "samples_num_alt_2": [],
    "variantId": "CMG.phase1_CMG_DEL_chr8_1792",
    "sortedTranscriptConsequences": [
      {
        "gene_symbol": "PKIA",
        "gene_id": "ENSG00000171033",
        "major_consequence": "NEAREST_TSS"
      }
    ],
    "genotypes": [
      {
        "sample_id": "GLE_4292_4_2",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE_4292_4_3",
        "gq": 1,
        "cn": 2,
        "num_alt": 1
      },
      {
        "sample_id": "GLE-4778-4-2-a",
        "gq": 1,
        "cn": 2,
        "num_alt": 1
      },
      {
        "sample_id": "GLE_4905_3_2",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "MCOP067",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "MWAR053",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE-3677-4-2-a",
        "gq": 5,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE-3677-4-4-a",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE-3871-4-2-a",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE_4397_4_2",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE_4397_4_3",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE-5279-3-3",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE_5483_3_3",
        "gq": 999,
        "cn": 1,
        "num_alt": 0
      },
      {
        "sample_id": "HIL_A5192_12_1",
        "gq": 1,
        "cn": 2,
        "num_alt": 1
      },
      {
        "sample_id": "MBEL001",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "MPAU036",
        "gq": 999,
        "cn": 1,
        "num_alt": 0
      },
      {
        "sample_id": "VS_ABC004_1",
        "gq": 999,
        "cn": 1,
        "num_alt": 0
      },
      {
        "sample_id": "VS_EU003_1",
        "gq": 70,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE-3386-4-4-a",
        "gq": 85,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE-3386-4-6-a",
        "gq": 999,
        "cn": 1,
        "num_alt": 0
      },
      {
        "sample_id": "GLE-3414-4-3-a",
        "gq": 999,
        "cn": 1,
        "num_alt": 0
      },
      {
        "sample_id": "GLE-3414-4-6-a",
        "gq": 120,
        "cn": 1,
        "num_alt": 0
      },
      {
        "sample_id": "GLE-3734-4-4-a",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE-3822-4-3-a",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE_3822_4_4",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE_4111_4_5",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "GLE_4292_4_1",
        "gq": 1,
        "cn": 2,
        "num_alt": 1
      },
      {
        "sample_id": "GLE-5279-3-1",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "HIL_A5192_21_1",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "MBEL122",
        "gq": 999,
        "cn": 1,
        "num_alt": 0
      },
      {
        "sample_id": "MCAI002",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "MCAI043",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "MCAI054",
        "gq": 999,
        "cn": 1,
        "num_alt": 0
      },
      {
        "sample_id": "MWAR044",
        "gq": 999,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "VS_EU003_2",
        "gq": 120,
        "cn": 2,
        "num_alt": 0
      },
      {
        "sample_id": "VS_EU003_3",
        "gq": 79,
        "cn": 2,
        "num_alt": 0
      }
    ],
    "sample_qs_0_to_10": [
      "GLE_4292_4_3",
      "GLE-4778-4-2-a",
      "GLE-3677-4-2-a",
      "HIL_A5192_12_1",
      "GLE_4292_4_1"
    ],
    "sample_qs_70_to_80": [
      "VS_EU003_1",
      "VS_EU003_3"
    ],
    "sample_qs_80_to_90": [
      "GLE-3386-4-4-a"
    ],
    "sample_qs_120_to_130": [
      "GLE-3414-4-6-a",
      "VS_EU003_2"
    ],
    "sample_qs_990_to_1000": [
      "GLE_4292_4_2",
      "GLE_4905_3_2",
      "MCOP067",
      "MWAR053",
      "GLE-3677-4-4-a",
      "GLE-3871-4-2-a",
      "GLE_4397_4_2",
      "GLE_4397_4_3",
      "GLE-5279-3-3",
      "GLE_5483_3_3",
      "MBEL001",
      "MPAU036",
      "VS_ABC004_1",
      "GLE-3386-4-6-a",
      "GLE-3414-4-3-a",
      "GLE-3734-4-4-a",
      "GLE-3822-4-3-a",
      "GLE_3822_4_4",
      "GLE_4111_4_5",
      "GLE-5279-3-1",
      "HIL_A5192_21_1",
      "MBEL122",
      "MCAI002",
      "MCAI043",
      "MCAI054",
      "MWAR044"
    ]
  }
}
```

2021-07-21 14:49 UTC, hanars requested changes

2021-07-21 14:49 UTC, hanars commented on sv_pipeline/genome/load_data.py
> +FIELDS = list(CORE_FIELDS.keys()) + list(DERIVED_FIELDS.keys()) + ['variantId', 'sortedTranscriptConsequences', 'genotypes'] +\
you could use the `SORTED_TRANS_CONSEQ` constant here as well

2021-07-21 14:49 UTC, hanars commented on sv_pipeline/genome/load_data.py
> +    rows = rows.annotate(**{TRANS_CONSEQ_TERMS: rows[TRANS_CONSEQ_TERMS]
It is much cleaner to just modify the function for this field in `DERIVED_FIELDS`

2021-07-21 19:54 UTC, hanars approved these changes
looks good to me!

2021-07-21 20:03 UTC, merged