Aw/disable flattened indices
broadinstitute/hail-elasticsearch-pipelines pull request #290
Opened 2021-11-23 16:27 UTC by averywpx

Resolved the issue occurred in #280 by disabling the flattened names in `properties` as well.

2021-11-23 17:56 UTC, hanars requested changes

2021-11-23 17:56 UTC, hanars commented on hail_scripts/elasticsearch/elasticsearch_utils.py
> +                flattened_fields = [key for key in properties if f"{es_field_name}_" in key]
So the key has to start with the prefix not just contain it, so it should not be `f"{es_field_name}_" in key` it should be `key.startswith(f'{es_field_name}_')

2021-11-23 19:52 UTC, hanars commented
looks good t me, @mike-w-wilson thoughts?

2021-11-23 20:23 UTC, mike-w-wilson commented
This looks good to me as well!

2021-11-23 20:23 UTC, mike-w-wilson approved these changes

2021-12-01 16:12 UTC, hanars approved these changes

2022-03-02 15:40 UTC, mike-w-wilson commented
@averywpx , @hanars I've tested this on our airflow2 instance and have gotten this error for `rg37_locus`, `sortedTranscriptConsequences` and now `genotypes`. Should I just continue removing the disable_index=True? This seems like it may be an issue outside of the nested fields?
```
'Mapping definition for [genotypes] has unsupported parameters:  [index : false]')
```

2022-03-02 15:48 UTC, hanars commented
`genotypes` is also a nested field so yeah I would just remove `disable_index=True` for that. I checked a successful index mapping, and only `sortedTranscriptConsequences` and  `genotypes` have type "nested". `rg37_locus` actually doesn't have a type at all, it has a nested "properties" dict that has the type for each sub-field, I guess because it is a single nested object instead of a list of nested objects (the 2 nested fields also have this "properties" dict). There are no other fields with these nested properties, so I think these should be the only affected fields

2022-03-02 17:51 UTC, mike-w-wilson commented
So the index grew ~20% larger..... the 2/16/2022 index is 21.2gb, today's is 27.4gb. I confirmed there is the same number of records in both so there must be something else going on.

2022-03-02 17:55 UTC, mike-w-wilson commented
Also, I just reran export, so this is the same variant and project MTs as the previous index

2022-03-02 18:08 UTC, mike-w-wilson commented
And now I'm a liar -- the data management page is now showing 21 GB for today... 😕

2022-03-02 20:04 UTC, hanars commented
so we're saying this doesn't actually save any space? Or that we aren't testing properly

2022-03-02 21:47 UTC, mike-w-wilson commented
It looks like it saved a tiny bit of space, 0.2 GB for this index. I'm not sure why it showed a larger index at first. Maybe it was reporting the size during a temp to data node transfer or something.

2022-03-03 13:34 UTC, mike-w-wilson commented
I've pushed a commit with the three fields disabled. Sorry for the confusion yesterday. The PR was tested properly. Even though it didn't save us a ton of space, looks like just 1%, I think we still merge this but would like to hear your thoughts @hanars on adding more complexity to the repo vs data savings. Also, I couldnt find if it is possible to disable indexing on nested field types in a different way but perhaps we would see larger savings if we could figure that out for genotypes in a different PR?

2022-03-03 15:20 UTC, hanars commented
I would say my intuition is to merge this as is, because while there is added complexity I don't think it's too much to maintain and there is some data saving. I think for the 3 nested-ish fields, my intuition is we would need to set `"enabled": False` for each sub-field of the nested properties dict, which should only be a couple more lines of code in the handling of `disable_index_for_fields`. I hope those fields will add more noticeable space saving (they are very big) but if we would rather merge this working, tested code now and add that additional functionality as a separate PR that would make sense to me

2022-03-04 15:07 UTC, merged